[Feature/add lift demo] Add hotel scenario
osrf/rmf_demos pull request #119
Opened 2020-08-26 04:11 UTC by MakinoharaShouko

This is the demo scenario I have been working on as part of Google Summer of Code. The map is a reduced version and the full version can be accessed [here](https://github.com/MakinoharaShouko/hotel). The full map consumes a huge amount of memory thus cannot run. This version is reduced so that the rmf_core can handle most requests. Though It still breaks when the request is long (especially for the MiR100 fleet)

2020-08-27 06:46 UTC, Kevinskwk requested changes
Thanks for the work! It looks great in the traffic_editor, but two things are stopping me from seeing this demo in gazebo:
1. As commented, the robot are now renamed. So all appearances of the branded robot names should be changed.
2. It seems that the names of the models you included are not up to date. You can try the following to update your thumbnails and models:
  - clone the latest of https://github.com/osrf/traffic_editor_assets into your `$HOME/.traffic_editor/assets/` directory
  - update the model names in your `building.yaml` file according to the latest thumbnails available
  - then do the following to download the new models:
  ```
cd ~/.gazebo/
mv models models-bak # just as a backup
mkdir models
cp -r models-bak/sun models/.
cp -r models-bak/ground_plane models/.
cd YOUR_WORKSPACE
rm -rf build/rmf_demo_maps install/rmf_demo_maps
source /opt/ros/eloquent/setup.bash
colcon guild --packages-up-to demos --cmake-args -DCMAKE_BUILD_TYPE=RELEASE
  ```

In addition, could you also add some descriptions and instructions on running the hotel demo in `README.md`? Thank you!

2020-08-27 08:10 UTC, Yadunund commented
It would be good to also update the `README.md` file with instructions to launch this world.

2020-08-28 00:12 UTC, MakinoharaShouko commented on demos/launch/hotel.launch.xml
> +    <let name="fleet_name" value="magni"/>
I have made the name changes to the hotel map and the launch file and also added the instruction part in `README.md`. There are some model thumbnails that I generated with `thumbnail_generator` so I left them untouched.

2020-08-28 03:09 UTC, Kevinskwk commented on demos/launch/hotel.launch.xml
> +    <let name="fleet_name" value="magni"/>
By generating model thumbnails, do you mean that you have included some custom models?

2020-08-28 03:11 UTC, MakinoharaShouko commented on demos/launch/hotel.launch.xml
> +    <let name="fleet_name" value="magni"/>
Yeah

2020-08-28 03:33 UTC, Kevinskwk commented
Thank you for the changes, I am able to launch the world now. Though there are still several minor issues, I guess I can quickly fix them after merging. Just to clarify, are all the doors and some lifts missing to reduce memory usage? Also, it would be great if you could add the link to the full version map in `README.md` so that people can still try if interested.

2020-08-28 03:40 UTC, Kevinskwk commented on demos/launch/hotel.launch.xml
> +    <let name="fleet_name" value="magni"/>
Okay, so where are the models placed in?

2020-08-28 03:54 UTC, MakinoharaShouko commented on demos/launch/hotel.launch.xml
> +    <let name="fleet_name" value="magni"/>
I downloaded them from ignition fuel. Some are from `~/.gazebo/models`

2020-08-28 04:01 UTC, MakinoharaShouko commented
Yeah I removed the doors and most lifts to reduce the memory usage. I have also attached the link to the full hotel repo

2020-08-28 04:02 UTC, Kevinskwk commented on demos/launch/hotel.launch.xml
> +    <let name="fleet_name" value="magni"/>
Oh ok, then it should be fine

2020-08-28 04:03 UTC, Kevinskwk approved these changes
Thanks for the work. I'll merge this PR first and then quickly fix some minor issues

2020-08-28 05:43 UTC, merged