Add Ignition simulation plugins and demos
osrf/rmf_demos pull request #152
Opened 2020-10-14 02:40 UTC by luca-della-vedova

This (large!) PR introduces support for Ignition Gazebo in RMF demos, it includes:

- Updates to map generation CMakeLists to generate Ignition maps as well.
- Ignition gazebo launch files, they are the same as the official launch files but have a _ign suffix (i.e. `office.launch.xml` becomes `office_ign.launch.xml`).
- Plugins refactorization: All the `rmf_demos_plugins` have been refactored in common library + ignition / gazebo wrapper, the same way it has been done in [traffic_editor](https://github.com/osrf/traffic_editor).
- A few additional dependencies to be built from source, including `ros_ign`, used for synchronizing Ignition and ROS clock, as well as `menge_core` used for crowd simulation (no crowd simulation demos have been generated yet).
- Updated documentation on how to install Ignition from either binaries or source.

For now all the simulations run with the DART physics engine. Support for the higher performance [TPE](https://community.gazebosim.org/t/announcing-new-physics-engine-tpe-trivial-physics-engine/629) is in progress, there is still a few features pending in the core libraries.

Testing any of the environments should be as simple as building the new packages in the yaml file, running `sudo apt install ignition-dome` and appending `use_ignition:=1` when launching demos through the `ros2 launch`.

2020-11-02 02:58 UTC, Yadunund requested changes
Thanks for this amazing effort to support demos with ignition. In evaluating this PR, I tried to launch the various demos in gazebo and ignition to test basic functionality (after performing a clean build). I ran into errors (mostly linking with `rmf_plugin_utils`) when trying to launch worlds as described below.

Office world: 
* Simulation crashes during startup when launched with gazebo (without fail each time). ```[gzserver-9] gzserver: symbol lookup error: /home/yadu/rmf_demos_ws/install/rmf_plugins_common/lib/libdispenser_common.so: undefined symbol: _ZN17rmf_plugins_utils14simulation_nowEd
[ERROR] [gzserver-9]: process has died [pid 9254, exit code 127, cmd 'gzserver --verbose -s libgazebo_ros_factory.so -s libgazebo_ros_init.so /home/yadu/rmf_demos_ws/install/rmf_demo_maps/share/rmf_demo_maps/maps/office/office.world'].```
Demangled symbol : ```rmf_plugins_utils::simulation_now(double)```

Airport world:
* Ign simulation crashes at launch with error: ```[ign-9] ign gazebo server: symbol lookup error: /home/yadu/rmf_demos_ws/install/rmf_plugins_common/lib/libreadonly_common.so: undefined symbol: _ZN17rmf_plugins_utils14simulation_nowEd```
Demangled symbol: ```rmf_plugins_utils::simulation_now(double)```

* Gazebo simulation crashes at launch with error ```[gzserver-9] [libprotobuf ERROR google/protobuf/descriptor_database.cc:58] File already exists in database: ignition/msgs/actor.proto
[gzserver-9] [libprotobuf FATAL google/protobuf/descriptor.cc:1358] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
[gzserver-9] terminate called after throwing an instance of 'google::protobuf::FatalException'
[gzserver-9]   what():  CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
[gzclient-10] [INFO] [1604284988.355876535] [gazebo_ros_node]: ROS was initialized without arguments.
[ERROR] [gzserver-9]: process has died [pid 10265, exit code -6, cmd 'gzserver --verbose -s libgazebo_ros_init.so -s libgazebo_ros_factory.so /home/yadu/rmf_demos_ws/install/rmf_demo_maps/share/rmf_demo_maps/maps/airport_terminal/airport_terminal.world'].
[gzserver-9] ```

2020-11-02 03:52 UTC, Yadunund commented
The linking problem related to `rmf_plugin_utils` was solved after another clean build, so that's great. Still facing issues with the airport world in gazebo. But I suspect it might be due to my workspace setup.

On a side note, since we have replaced the robot placeholders with robot models in the airport world, we can go ahead and delete the `/demos/scripts/` folder

2020-11-02 10:03 UTC, tanyouliang95 commented
Went through a clean build, yet still facing issue on crowdsim plugin: 
```
[gzserver-10] gzserver: symbol lookup error: /home/youliang/rmf_ws/install/building_gazebo_plugins/lib/libcrowd_simulator.so: undefined symbol: _ZNK15crowd_simulator17CrowdSimInterface6loggerEv
[ERROR] [gzserver-10]: process has died [pid 25542, exit code 127, cmd 'gzserver --verbose -s libgazebo_ros_init.so -s libgazebo_ros_factory.so /home/youliang/rmf_ws/install/cag_maps/share/cag_maps/maps/terminal3/terminal3.world'].
```

2020-11-02 10:23 UTC, luca-della-vedova commented
> Went through a clean build, yet still facing issue on crowdsim plugin:
> 
> ```
> [gzserver-10] gzserver: symbol lookup error: /home/youliang/rmf_ws/install/building_gazebo_plugins/lib/libcrowd_simulator.so: undefined symbol: _ZNK15crowd_simulator17CrowdSimInterface6loggerEv
> [ERROR] [gzserver-10]: process has died [pid 25542, exit code 127, cmd 'gzserver --verbose -s libgazebo_ros_init.so -s libgazebo_ros_factory.so /home/youliang/rmf_ws/install/cag_maps/share/cag_maps/maps/terminal3/terminal3.world'].
> ```

Do you have the latest traffic editor master?

2020-11-02 10:27 UTC, tanyouliang95 commented
@luca-della-vedova  yes, latest `traffic_editor`. Btw, I shouldnt mention this issue here as it is relevant to `traffic-editor`

2020-11-03 07:54 UTC, luca-della-vedova commented
> @luca-della-vedova yes, latest `traffic_editor`. Btw, I shouldnt mention this issue here as it is relevant to `traffic-editor`

It shouldn't be an issue but did you [include menge](https://github.com/osrf/rmf_demos/blob/master/rmf_demos.repos#L22-L25) in your workspace?

2020-11-04 15:14 UTC, Yadunund commented
Did another clean build after pulling master on `traffic_editor`.

* Airport world crashes during launch with error 
```[gzserver-9] [libprotobuf ERROR google/protobuf/descriptor_database.cc:58] File already exists in database: ignition/msgs/actor.proto
[gzserver-9] [libprotobuf FATAL google/protobuf/descriptor.cc:1358] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
[gzserver-9] terminate called after throwing an instance of 'google::protobuf::FatalException'
[gzserver-9]   what():  CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
[gzclient-10] [INFO] [1604502616.812901911] [gazebo_ros_node]: ROS was initialized without arguments.
[ERROR] [gzserver-9]: process has died [pid 86668, exit code -6, cmd 'gzserver --verbose -s libgazebo_ros_init.so -s libgazebo_ros_factory.so /home/yadu/ws_rmf_demos/install/rmf_demo_maps/share/rmf_demo_maps/maps/airport_terminal/airport_terminal.world'].
```

* All the ignition worlds crash during launch with error 
```
[ign-9] ign gazebo server: symbol lookup error: /home/yadu/ws_rmf_demos/install/building_ignition_plugins/lib/libslotcar.so: undefined symbol: _ZN19building_sim_common13SlotcarCommon14set_model_nameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

2020-11-10 02:39 UTC, luca-della-vedova commented
OK!
> * Airport world crashes during launch with error
> 
> ```
> [gzserver-9] [libprotobuf FATAL google/protobuf/descriptor.cc:1358] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
> [gzserver-9] terminate called after throwing an instance of 'google::protobuf::FatalException'
> [gzserver-9]   what():  CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
> [gzclient-10] [INFO] [1604502616.812901911] [gazebo_ros_node]: ROS was initialized without arguments.
> [ERROR] [gzserver-9]: process has died [pid 86668, exit code -6, cmd 'gzserver --verbose -s libgazebo_ros_init.so -s libgazebo_ros_factory.so /home/yadu/ws_rmf_demos/install/rmf_demo_maps/share/rmf_demo_maps/maps/airport_terminal/airport_terminal.world'].
> ```

"Fixed" in the last commit. I had to comment out the ignition caddy plugin which means the caddy in ignition is not working but at least it won't break the existing simulation, we can figure out how to load its plugin in a future PR.

> * All the ignition worlds crash during launch with error
> 
> ```
> [ign-9] ign gazebo server: symbol lookup error: /home/yadu/ws_rmf_demos/install/building_ignition_plugins/lib/libslotcar.so: undefined symbol: _ZN19building_sim_common13SlotcarCommon14set_model_nameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
> ```

This should be fixed in the traffic_editor PR [#262](https://github.com/osrf/traffic_editor/pull/262)

2020-11-11 14:26 UTC, Yadunund approved these changes
Thanks for addressing the remaining issues!

2020-11-17 09:12 UTC, merged