Create initial light tuning plugin
osrf/rmf_demos pull request #166
Opened 2020-11-30 00:52 UTC by mrushyendra

2020-12-02 01:25 UTC, luca-della-vedova commented
Just a quick check, do you think it would be possible to change the way the color is chosen from three numbers to a more familiar "palette" similar to what is found in image editing software? Something like this:
![image](https://user-images.githubusercontent.com/9111558/100815714-9168fd80-347f-11eb-9509-0f38507443e6.png)

> to update lights in real time - i.e. not have to select create each time you want to re-render the light (though this does not currently seem feasible due to the time the create/remove service takes)
This would be quite interesting I think, from what I understand you mean that you can't run it at every loop iteration since the service can be quite slow (which I agree with). An alternative approach could be to cache the state of the light parameters / object pose and set a `dirty` bit whenever any parameter is updated, then respawn the light and clear the `dirty` bit. Does it make sense?

2020-12-02 04:01 UTC, mrushyendra commented
I've never tried implementing a color picker, but it definitely seems doable. As for the updating of lights, I imagined something even more responsive (e.g. lights change continuously as you drag the sliders, or if you move the cube to change its pose), but I think updating them whenever an edit is finished is a good middle ground.

2020-12-03 10:02 UTC, luca-della-vedova requested changes
Generally looks good! A few minor questions and feedback around.
Other high level feedback:

Did you manage to get spot lights to work? I created a white spot light and it seems to make everything in its field black instead (attached screenshot)
![image](https://user-images.githubusercontent.com/9111558/100993694-b0a38000-3590-11eb-9f68-99425ac87312.png)

I wonder if there is a simple way to hide the spot light parameters when the light type is not Spot, but if this requires too much additional code / changes it's probably OK to keep it this way.

[just saw the color picker and it's awesome!]

2020-12-04 04:24 UTC, mrushyendra commented
I think the black circle occurs for the spotlight when the inner angle is set to a bigger value than the outer angle. Here's a screenshot of the params for a working one: 
![Screenshot from 2020-12-04 09-27-29](https://user-images.githubusercontent.com/22248849/101121496-42f86200-362b-11eb-89d1-2606adde50d8.png)
I also changed the code to hide the spotlight-specific params when not needed.

2020-12-04 04:28 UTC, luca-della-vedova commented
Oh that makes sense :sweat_smile: feature wise this looks good to me, let me know if you want more time to look at the automatic update seg fault issue.

2020-12-04 04:29 UTC, mrushyendra commented on rmf_demo_plugins/rmf_ignition_plugins/src/LightTuning/LightTuning.cpp
> +    }
True, I removed the case since it seems very unlikely to happen, and even then Ignition would simply issue a warning anyway.

2020-12-04 04:31 UTC, mrushyendra commented on rmf_demo_plugins/rmf_ignition_plugins/src/LightTuning/LightTuning.cpp
> +    });
Changed it to check against a set of pre populated names before creating the light.

2020-12-04 04:32 UTC, mrushyendra commented on rmf_demo_plugins/rmf_ignition_plugins/src/LightTuning/LightTuning.cpp
> +  }
Guess I was being extra cautious :)

2020-12-04 04:43 UTC, mrushyendra commented on rmf_demo_plugins/rmf_ignition_plugins/src/LightTuning/LightTuning.cpp
> +  // created/removed in Ignition in the order requested.
Generally, sending one call per light per Update iteration seems to work fine in practice. Any faster, and occasionally seg faults seems to occur in ignition itself during the rendering process (even after a success callback is received). In theory, the ignition documentation doesn't say much about what order the calls would be executed.

2020-12-04 08:11 UTC, mrushyendra commented
Pushed some additional changes that allow for the lights to be updated as you move the sliders/finish typing. 

Sending create and remove requests very quickly after one another can still cause a seg fault in Ignition, I believe because of a lag between entity creation/removal and the actual rendering itself, but I believe it shouldn't happen with this plugin because the Qt signals have been chosen such that they don't fire too soon after one another.

2020-12-08 06:27 UTC, luca-della-vedova commented
This is really really nice, thanks for iterating!

2020-12-08 06:27 UTC, luca-della-vedova approved these changes

2020-12-08 06:28 UTC, merged