Traffic Light Scenarios
osrf/rmf_demos pull request #168
Opened 2020-12-04 08:23 UTC by mxgrey

This PR provides the testing scenarios for the traffic light fleet adapter introduced in https://github.com/osrf/rmf_core/pull/226.

2020-12-07 07:34 UTC, Yadunund requested changes
All the scenarios work great!
Before we merge this in, could we modify `battle_royale.launch.xml`, `triple_H.launch.xml` and `office_mock_traffic_light.launch.xml` to also support launching with `ignition`? We can follow the template in the latest [`master`](https://github.com/osrf/rmf_demos/blob/de780c181c36261b80025bbf8d50713f1367f68e/demos/launch/office.launch.xml#L14-L61)

2020-12-08 06:01 UTC, mxgrey commented
I felt there was a lot of code duplication between the different launch files, so I've refactored how the simulations get launched across all the different maps.

I don't have ignition installed, so we should definitely have an ignition user test out whether these changes still work for launching ignition.

2020-12-08 07:52 UTC, Yadunund commented on demos/launch/triple_H.launch.xml
> +    <arg name="map_name" value="office" />
`value` should equal `triple_H` here

2020-12-08 07:56 UTC, mxgrey commented on demos/launch/triple_H.launch.xml
> +    <arg name="map_name" value="office" />
Fixed!

2020-12-08 08:51 UTC, Yadunund approved these changes
Thank you for cleaning up the launch files! Ignition and gazebo simulations work as expected :+1:

2020-12-09 07:22 UTC, merged